version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: install gcc, python3
          command: apt-get update && apt-get install -y gcc python3
      - run:
          name: gcc version check
          command: echo `gcc --version`
      - run:
          name: test all
          command: |
            for dirname in */; do
              echo $dirname;
              cd $dirname;

              for files in *.c; do
                gcc -o ${files%.c}.out $files;
                ./${files%.c}.out
                cat output.txt
              done;

              cd ..;
            done;
