version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: install gcc, python3
          command: apt-get update && apt-get install -y gcc python3
      - run:
          name: gcc version check
          command: echo `gcc --version`
      - run:
          name: test all
          command: |
            for dirname in */; do
              if [[ $dirname != .circleci ]]; then
                echo $dirname;
                cd $dirname;

                for files in *.c; do
                  gcc -o ${files%.c}.out $files
                done;

                if [[ -e "test.py" ]]; then
                  python3 test.py;
                fi;
                cd ..;
              fi;
            done;
        - run:
            name: push binary
            command: |
              git config credential.helper 'cache --timeout=120'
              git config user.email "revsic99@gmail.com"
              git config user.name "revsic"
              git add *
              git commit -m "ci, Add binary"
              git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com/revsic/HYU-CSE2010.git master
